import streamlit as st

st.set_page_config(
    page_title="Notes from the wards",
    page_icon="👋",
)
st.markdown("# Notes from the wards")
# st.sidebar.header("Notes from the Command-line")

st.write("# On the narrow way  - Second Sunday of Advent Dec 8, 2024")

st.markdown(
    """
In the Philippines during this time, clerks often are asked to help with preparations for “Christmas parties” from blowing balloons to judging the talent show. The mood is rather festive; each duty seems lighter amidst the realities of sickness personal to each patient. 

Paragraph about objective and subjective findings. 

Generating a list of differential diagnoses and subsequently formulating a diagnostic plan. 

What is often missed in medicine is the art of prognosis. Art and medicine being about practice. Prognosis being practiced varies from specialty to specialty. Certainly emergency medicine are prognostic experts on emergencies that can potentially kill the patient. Psychiatry less certain. (develop specialties that are more physical / physiological to more about the mind/spirit. 

Prognosis is important yet underlooked. Spiritually with advent, prognosis of our souls requires joy because the prognosis is always good. As is often put as an epigraph in many a medical student presentations, “always begin with the end in mind”, a quote often attributed to Aristotle. Yet medical students are actually encouraged to put their biases about the cases aside and focus on the history taking and the objective facts that can come about. Since medical students are awaiting the beginning of their career, it suffices to say that the preparation involved in becoming a doctor involves a lot of sacrifice.

Advent similarities as a period of waiting. Often old testament imagery points towards an uncertain future that doesn’t seem to make much sense if read alone. Rather, the old is revealed in the new and the new is hidden in the old (as Augustine says). Signs and prophecies seen in the old testament are fulfilled in the new. Likewise, the medical student’s esoteric studies in the cellular and molecular level of biology is revealed in the clinical cases that have genetic links. 


Points/ discussion/ leading to conclusion: 
Such a paradox actually fits the Church’s proclamation of the Gospel. In this period of Advent, the emphasis on hope yet is actually also a period of fasting and penance– a so called “penitential season.” What emerges from resolving this apparent dissonance is a deeper understanding of Joy. Much like the Church’s understanding of love, joy goes beyond emotion and 





"""
)


st.write("# Padres Y Doctores - July 16, 2024")

st.markdown(
"""
Dear Fr. Al,
	I’m writing to you now during my PM duty (7 pm to 7 am)– the 2nd shift of my time as a clerk– under an hour after a code blue started for 13 minutes. I was with my fellow clerk Ju and our senior intern Lee as we were answering questions given by Doktora Erika, the senior fellow for the ICU critical care service. We were discussing the use of pressors– drugs that work to activate parts of the body that can increase blood pressure. I had just come back to the question and answer from transferring one of the patients that we had to monitor as a team of students. The patient was conversant and in good spirits. She looked at my breast pocket and commented with intrigue on the logo. The family also came with and noted my last name. All of these pleasantries for one of my first few times on duty until doc Erika quietly but quickly left one of the patient rooms we were in to attend to the special ICU units. We followed suit only to see a team of nurses attending to a code blue.

	Doctors gathered around, and the three of us sheepishly were in the back against the wall watching as a gloved nurse was delivering compressions to the chest wall. I’m not at liberty to discuss more specific patient details and would not want to violate ethical norms anyway, however I can write about the experience. Fr. Al, I think your well-wishing for me before clerkship started had come in full force as the progression of those 13 minutes of code felt like a procession from body to spirit. Not merely an object but an embodied spirit. I’m sure all these nurses and doctors around us (and even intern Lee) have seen this many times, but I got so wrapped up in what was going on and quickly started muttering Hail Marys under my breath, while holding the small rosary bracelet you gave me. Each nurse in turn would deliver chest compressions every 30, 60 or 90 seconds (progressively longer intervals) before checking the rhythm of the patient’s heart. We don’t just shock the heart if the patient’s heart is flatlining. This and pulseless tachycardia are known as non-shockable rhythms. The goal of the Acute Care Life Support (ACLS) protocol was to restart the heart by getting it to start pumping a “shockable” rhythm again. In the background I overheard the nurses noting the progression. The compressions corresponded to what was shown on the monitor but when they were temporarily withdrawn, only flat lines were measured. Doc Erika would say to push another round of “epi” (or epinephrine), which in fact is one of the pressors we were discussing not more than 30 minutes prior. 

	This was when emotions of various kinds started flooding in. I could hear footsteps coming and faint female cry mixed with cries to “kuya”. As the sound came closer, I could hear a male voice shouting “Love you, ma!” It was the patient’s family, I realized. A moment later, the male emerged through the door dressed in a blue jersey while the female stayed outside crying and only noticeable in my periphery. It soon dawned on me that I remember this blue jersey. He was at mass earlier when I came to medical city for my daily mass, I was kneeling after communion and he had just received the host. I remembered noticing the jersey and then realized that he’s probably family of a family member here. Little did I know I would see him again a few hours later. 
	
    I started to reflexively tear up but a as soon as I realized it, I tried to suppress it as I didn’t want to convey despair or communicate hopelessness about the code. In fact, I was full of a naïve hope. In between the cycle of Hail Marys, Come Holy Spirit, and Lord’s prayers, I would pray Lord heal this patient, please. And my pleas became more and more desperate as the code went on. I wondered where my part in all this was. I was trying to find meaning amidst sounds of crying, and more family members being called in. I could see other doctors come in and discuss the case in one side and the family on the other side. I knew the blue jerseyed “kuya” was trying to keep it together as his sister pleaded with him saying “hindi ko kaya” (I can’t handle this). I thought of other phrases too– Talitha koum, or “If I could only touch”. I wondered if this whole thing was for me to realize that I was negligent of my own medical education– that I wasn’t studying hard enough and that I should’ve been able to answer all the questions from doc Jika about vasopressors. The counterfactual creeped in– if I don’t study hard, then the next patient will die. Upon short reflection, I realized the error of the reasoning, which was enough to snap me back to reality and humble me. I remember from the book of wisdom God did not create death, nor does he rejoice in the destruction of the living. Rather, He sent His son to put death to death and bear eternal life in heaven. I was also quick to realize that I’m not a deity and neither are my prayers some kind of magic chant to heal her. And yet I still prayed. But my prayer changed. Not my will but…
	
    Perhaps it was around the 5th or 6th round of epinephrine and compressions where one of the resident doctors went up to me, Ju and Lee and extended a box of sterile gloves motioning us to get them. I looked up and she said “you’re going to do compressions”. I quickly got the gloves and put it on, only momentarily being distracted from the string of flowers I was praying. As I slowly walked up, the nurse asked “ikaw ba yung mag-cocompressions?” I nodded and then they motioned me to take off my jacked because “baka matalsikan ka”. So I took it off and put it in the nearby meeting room, where I’m writing this letter. I went back and then they motioned me again to remove my ID. After this, I put some alcohol on my gloves from the back and forth and then lined up. I relieved the nurse wearing a sterile gown and started to compress. The other resident started to guide me, reminding me to interlock my fingers. My own epinephrine started firing in and I started performing CPR while shouting in my head more hail Marys. I wasn’t crying anymore but I did yell from my heart “Out of the depths I cry to you, Lord, Lord hear my voice. Let your voice be attentive to my appeal”. I was told not to compress too fast, and then remembered from my basic life support training that we should let the chest recoil so that the heart can fill up blood again. I took this in mind as I delivered more forceful contractions with more recoil time. I couldn’t hear anything else except the calm instructions and guidance from my resident and the patient’s chest through my hands– sometimes feeling a gurgling coming from her heart. ‘Was she giving up?’, I thought. 
	
    “1 more minute until rhythm check”, I heard the nurses declare. At this point I glanced at the patient and saw her face. It was at this point that I remembered she was a person– not just a body and neither just a soul– but an embodied soul. I also realized that here is the limit of medicine. It’s not as well-demarcated as I thought; quite fuzzy. And yet, it was clear after the nurse shouted “hands off CPR, rhythm check” that these compressions were more and more about me and Julia more than for the patient (not entirely, though). When Julia came to take over and started to do her CPR, a small stool was handed over from the other side for her to step on. I wondered why’d they make her stop as the handing over was happening. The realization then hit home– they wouldn’t have mobilized the medical students unless it was the inevitable. The patient was dying if not already dead. As I pondered this, the blue jerseyed Kuya walked in and looked over his mother (or grandmother), saying once more “ma, I love you”. 
	
    I thought Lee was going to have a try but the resident was explaining something to her. Slowly the extra nurses on standby to compress started shuffling out. I noticed the cardiac monitor’s numbers slowly start to dwindle. The red flatline that remained was silent. As I went back to my spot by the wall, I noticed doc Erika wasn’t by the entrance of the patient’s unit, where she looked like a captain of the ship trying to steer through the streams of critical care. The resident doctor said “thank you doctors, sige na you guys can wash your hands”. I then went out to get my coat and saw in my peripheral doc Jika speaking with what looked like the blue jerseyed Kuya’s father, and likely son of the patient rubbing his eye with his palm and listening. After I got my coat I walked down that hallway and then saw another resident doctor ask the father if he would like him to call a priest. The man said “yes if it’s available”. 

    I then continued proceeding to the nurse’s station and after getting passed it, to the exit of the ICU, where I saw the crying little sister on the floor with her blue jerseyed Kuya pacing back and forth. I didn’t want to disturb them in this time so I continued outside and to the bathroom to do proper handwashing techniques. After returning, they were still there. 
    
    At this point, I realized that there was some kind of promise of the Divine Mercy wherein if one would pray the divine mercy chaplet at someone’s side, then I think the person would be freed from having to go to purgatory. I wasn’t sure but I whipped out my rosary bracelet and started to pray the chaplet outside. At some point a curtain was drawn and family members slowly started stepping through. I was pacing outside in the hallway near where the special ICU unit entrance was, sometimes leaning on the wall right beside the door and the fire extinguisher. I think I was on the 3rd decade when Julia and intern Lei went out and before they said anything I said “I’m okay” before they then asked simultaneously “are you okay”. They then said they that doc Erika said we should take a break and they’d get food in the resident’s quarters. I said they could go on ahead. They asked me if I’m fine again, I smiled. 
    
    After finishing the chaplet, I went back inside and got my breviary. I then flipped through the pages until I got to the “office of the dead”. I found a black plastic chair and sat down facing the open door that looks on to the room and proceeded: “God, come to my assistance, Lord make haste to help me.” The psalms included Psalm 121 (I lift up my eyes to the mountains from where shall come my help? My help shall come from the Lord who made heaven and earth), a canticle from Philippians (so that at Jesus’ name every knee must bend), and the earlier quoted Psalm 130 (Out of the depths I cry to you, O lord, Lord, hear my voice). The reading was from 1 Corinthians 15– “O death, where is your victory? O death ,where is your sting?”. By the time I got to the closing prayer, I remembered the patient’s last name and aptly so as naming the person was part of it:
    
    Lord, hear our prayers. By raising your Son from the dead, you have given us faith. Strengthen our hope that ___, our sister, will share in his resurrection. We ask this through our Lord Jesus Christ, your Son, who lives and reigns with you and the Holy Spirit. God, forever and ever. Amen.
    
    + May the Lord bless us, protect us from all evil, and bring us to eternal life. Amen.
    
    At this very moment, I saw a pair of black sandals, trousers and black short sleeved collared shirt and a strip of purple. It was then that I realized it was Fr. LQ– the chaplain. He was holding two red books in his right hand as he walked through the door and side-hugged the lady standing outside. I wanted to call out to him (I’m sure he saw me as I was praying)– but I thought better of it. I wanted to ask him whether the patient was enrolled in the scapular. I didn’t see any but given that today is the feast of our Lady of Mount Carmel, I figured maybe it was timely to ask. But you know, it really felt like I was a paramedic giving basic life support for the patient only to stop to let the doctor handle things from here. I know this in part because the office of the dead when offered for a person who has died confers a partial indulgence, but you priests can give the apostolic pardon and the sacraments. 
    
    Either way, we each have a role to play. And just as it is ontologically true that the priest is higher than the married person, I also give deference as a doctor of the body to the doctor of the soul. In both cases, the roles are ontologically set from the source of all being either way. I recall the gospel reading of a few days prior: “do not be afraid of those who can destroy the body… but fear the one who can destroy both body and soul” or something to that effect. 
    
    This leads me to reflect on my journey and my own discernment. It’s only been two days here and up until this point of my very short clerk life, I couldn’t have been any more amazed and inspired by what critical care medicine in the ICU demands. After this turning point, I was quickly reminded of the reality of this profession. From my vantage point, I can see a paradox between doctors and priests. Before the white coating ceremony of our medical school last Saturday– we had a thanksgiving mass. Our priest presider was Fr. RS, from one of those orders that administer our school. When he delivered his homily, he spoke briefly about his time in medical school and even rotating in PGH. He described being burnt out– seeing patients only as cases or problems to be solved– and ultimately quitting. He then made a joke saying if you end up quitting med, “don’t worry you’ll be a priest or a madre!” before quickly changing gears and saying that “maybe if I were a little less selfish and better formed, then I would be standing here as a doctor today” but the Lord has greater plans for us. He mentioned that he is a formator for Jesuits and of course since he’s also a doctor the Jesuits in formation would come to him for any medical issues. He said that he wasn’t afraid in giving them advice or treating them because if worse comes to worse he can “turn on priest mode and administer the sacraments and give last rites”, which he joked to a wave of chuckles. 
    
    But this is indeed the paradox I see. It is in a sense harder to be a doctor than it is a priest. Of course, there is a Thomistic nuance to be said here (certainly the stakes are harder on the priest for as the saying goes if a man falls goes astray only he goes astray but if a priest goes astray then so does his flock) and indeed Fr. Sian being both a priest and doctor demonstrates this nuance well. So why is it harder to be a doctor? I suppose the difficulty doesn’t lie in its content but in its uncertainty. We learn general truths or “universals” for the science of medicine yet have to apply it as an art to this particular person. One of the fathers of medicine displays this point well (and I happen to have his writings on me along with my breviary): 
    
    
    “Certain physicians and philosophers assert that nobody can know medicine who is ignorant what a man is; he who would treat patients properly must, they say, learn this. But the question they raise is one for philosophy; it is the province of those who, like Empedocles, have written on natural science, what man is from the beginning, how he came into being at the first, and from what elements he was originally constructed. But my view is, first, that all that philosophers or physicians have said or written on natural science no more pertains to medicine than painting. I also hold that clear knowledge about natural science can be acquired from medicine and from no other source, and that one can attain this knowledge when medicine itself has been properly comprehended” (Hippocrates: “Ancient Medicine”)
	
    We laud Hippocrates for his great effort and incredible insight, yet it only goes so far– medicine has largely been even less comprehensible than before, despite having a little knowledge about “what man is from the beginning, how he came into being at the first, and from what elements he was originally constructed” (i.e. DNA, fertilization, carbon, water, etc.). But Hippocrates wasn’t a Cartesian (far from it both conceptually and in time). I’m sure you know that natural science was conceived more broadly as a concept here (and of course the questions are indeed more suited in our age for “philosophy”). Why I think the speculation at the time didn’t pertain to medicine is precisely because it is not an embodied account. He makes reference to painting as an additional example for the same reason– for it to be appreciated, it has to be done by someone who is embodied or is “bodying-forth” (so to speak). This ties in with the second claim– that clear knowledge about natural science can be acquired only from medicine and no other source. It is in the great divine knowledge that we can then fill in Hippocrates’ gaps, for it is indeed from Jesus Christ, our Savior and Lord, who, in taking a human nature, has made clear knowledge (“the good news”) from the Divine Physician, who embodies medicine itself– for “those who are well have no need of a physician, but those who are sick. I came not to call the righteous, but sinners” (Mk 2:17). It indeed takes grace, something that seems to be outside medicine for medicine to “work” in a way that is enduringly fruitful. For the priest, there is grace already ontologically in the soul of the priest. His faith is one thing but it is the faithfulness of God to His covenant He makes with us that the sacraments are made truly present– it is not the priest who gives the service in mass but the Lord who works en masse. 
	
    This is the way in which I contend that it is harder to be a doctor, especially in these trying times. For there is no certainty in medicine, just generalizations that aren’t truly “universal” – as many counter examples of particular people can arise. And it indeed can’t be truly comprehended “rationally”; miracles bear witness to this false perspective. The wisdom of the world is folly and weaker than the foolishness of God– and the weakness of God is stronger than the strength of man. To tug at a personal analogy, it is indeed seemingly harder as well for the married couple as you sigh in relief not having to go through it– after hearing us describe them– that also arguably parallels the physician and patient pairing. I argue all this without even mentioning how much secularity one has to deal with as a doctor compared to the priest who tends to minister to the faithful. Yet, to put it even more bluntly, the priest tends to minister to the faithful, who are often doctors themselves to also go out into the world largely secular and to preach the gospel by their lives.
	
    Nevertheless, there are indeed parallels. The health that physicians try to give to patients is something that was not his gift. It is the same with faith, for even the most seemingly faithless heathen that ends up converting to the priest’s ministering develops or receives faith that is not the faith of the priest, but rather from something– someone– greater. 
    
    I look back at the code blue that happened in mere moments, but will carry it for all my life. For I have seen grace unfold but not in the way that I liked. And yet in His Divine and infinite Wisdom, it was through mercy that we were to behold His Kingdom. For while the hearts of the family cried out for justice. What happened at the end was peace and forgiveness. And peace came from certainty. Death eventually was ascertained from a medical perspective, and certainly in faith the Lord is faithful to His covenant, even unto the end. For in putting death to death, medicine is no longer a slow burn tragedy, but rather became a most healing remedy concocted by the Divine Physician– on earth as it is in heaven. Thy will be done. Thy kingdom come. Amen. 
    
    Please pray for the patient who recently passed, that her soul may rest in peace and please continue praying for me. I am going to become a doctor, and I dare hope to be a good one. A psalm today from the breviary that touched me was an excerpt from Psalm 119 prefaced by “I give you a new commandment: love one another as I have loved you” (John 13:34) and starts: 
    
    “Lord, how I love your law! It is ever in my mind. Your command makes me wiser than my foes; for it is mine for ever. I have more insight than all who teach me for I ponder your will” 
    
    I thought about this initially in the context of my senior doctors teaching me, but then I remembered that the gospel teaches us that law finds its fulfillment in love. Indeed, “kindness and truth will meet. Justice and peace shall kiss” (Ps 85-11-12). 
    
    Thank you in advance for spending this time with me reading this, through your ministry in administering the sacraments, and for enkindling in me a personal relationship with Jesus. 
    
    Sincerely yours on this Feast of Our Lady of Mount Carmel,

    [Wardman]

    P.S. I prayed vespers earlier in the Chapel and couldn’t be more thankful and grateful to be here. Making an act of spiritual communion, I offered it back to Him and recalled a bit earlier to receiving actual communion earlier. After the prayers of the faithful, the priest added “and we pray for all doctors, nurses, and medical staff of the medical city… we pray”– and I realized in a shiver that I was part of this petition– Lord, hear our prayer– because with the Lord there is mercy and fullness of redemption, Israel indeed he will redeem from all its iniquity. Gloria patri…

"""
)